# Generated by Django 5.2.7 on 2025-12-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0006_booking_rated_at_booking_rating_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
