# Generated by Django 5.2.6 on 2025-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0007_alter_booking_status_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='price',
        ),
    ]
